config/routes.rb
Rails.application.routes.draw do
  root 'brands#index'
  resources :brands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brand = Brand.order("RANDOM()").first
  end

  def new
    @brand = Brand.new
  end

  def create
    Brand.create(brand_params)
    redirect_to root_path
  end


  private

  def brand_params
    params.require(:brand).permit(:designer)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/index.html.erb
<h1><%= @brand.designer %></h1>

app/views/brands/new.html.erb
<h1>WHAT ARE YOU WEARING?</h1>
<%= simple_form_for @brand do |f| %>
  <%= f.input :designer %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wearware</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="row">
      <div class="col-3">
       <%= link_to root_path, class: 'logo' do %>
        <div class="circle">
          <br />
          WEARwares
          <br />
        </div>
       <% end %>
      </div>
      <div class="col-4 slogan">
        The latest in streetwear and couture.
      </div>
      <div class="col-5 links">
        <%= link_to 'Chime In', new_brand_path %>
        <%= link_to 'About Wearwares', '#' %>
      </div>
    </header>

    <hr />

    <br class="clear" />
    
    <div class="container">
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-6">
            <%= link_to "Browse trending designers", root_path, class: 'next-designer' %>
          </div>
        </div>
      </div>
    </div>


  </body>
</html>